[package]
name = "rustception"
version = "0.1.0"
authors = ["skodt", "sakarah"]
build = "build.rs"

[build-dependencies]
lalrpop = "0.13.1"

[dependencies]
lalrpop-util = "0.13.1"

[features]
default = []
borrow_log = []
